theme: jekyll-theme-tactile
repository: blekenbleu/microscope
#github: [metadata]
#markdown: CommonMarkGhPages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blekenbleu.github.io/microscope" # the base hostname & protocol for your site
